# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 백현성
title: Back-end System engineer
email: lamoreOrigin@gmail.com
website: www.github.com/ChopinNocturneOrigin

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: 자기소개
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & <mark>Springboot</mark> / Nodejs & <mark>React</mark> 기반 Back-end system engineer 입사 희망자 입니다. LGCNS <mark>대법원 공공 Payment Gateway</mark>(이하 PG)/ 정부24 PG/ LGCNS PG 서비스 운영을 통한 대규모 시스템 운영 경험이 있으며, 그외 Linux 환경하에 nginx/Springboot/Orcale server 를  Docker로 구성하여 배포하고, Apache web server/ PHP/ MySQL를 이용한 홈페이지 제작 및 운영 경험이 있습니다.

  안정된 서비스를 목표로 프로그래밍하는 것을 언제나 고민하고 있습니다.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: 경력 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 이커머스테크
        link: www.ectech.co.kr
        sub_title: LGCNS 플랫폼운영팀 파견직 대리
        caption: 2018.06 - 2020.10
        quote: >
          월 접속 평균 400만 규모의 Payment Gateway 서비스
        description: | # this will include new lines to allow paragraphs
            대한민국 대법원 공공 PG 서비스 / 정부24 / LGCNS CNSPay 운영 및 관리
            - Preventive Management : 월 1회
            - 장애대응 비상훈련 : 분기별 1회
            - Business continuity Planning(사업연속성계획) 훈련 : 년 1회
            - Deployment : Jenkins 활용
            - 퍼포먼스 관리, 가동률 보고, 월간/분기 보고 등 각종 운영관련 보고

      - title: 가우리컴
        sub_title: 실장
        caption: 2008.04 - 2018.04
        #quote: >
        description: | # this will include new lines to allow paragraphs
            - 컴퓨터 조립 / 수리
            - O/S 및 프로그램 설치
            - S/W 트러블 솔루션 제공
            - CI / 명함 디자인

      - title: 사운드플러스
        sub_title: 홈페이지 제작 대리
        caption: 2004.04 - 2005.04
        #quote: >
        description: | # this will include new lines to allow paragraphs
            - 국/내외 회사 홍보 홈페이지 작성
            - 해외 홍보 업무 (Germany Frankfrurt prolight & sound 2004 국제음향기기전 전시회)
            - CI / 제품 메뉴얼 제작

      - title: 용산와
        sub_title: 홈페이지 유지보수 업무
        caption: 2003.07 - 2004.01
        #quote: >
        description: | # this will include new lines to allow paragraphs
            - 컴퓨터 쇼핑몰 유지보수

  - title: 교육 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 자바(Java)기반 풀스택 개발자 with react & node.js 과정
        caption: 2023.03 - 2023.08
        sub_title: 이젠 아카데미 신촌 (정부지원 직업훈련 과정)
        quote: >
          Springboot, Mybatis, node.js 및 react 교육 및 교육과정을 활용한 프로젝트 진행
        description: | # this will include new lines to allow paragraphs
          교육 과정 중 습득한 스킬
          - Java, ES6, Spring Framework, Springboot, node.js, Express framework
          - Mybatis, Oracle RDBMS (PL/SQL), MySQL, MongoDB
          - HTML5, CSS3
          교육 과정 중 진행한 프로젝트
          - 휴대폰 온라인 가입 사이트 : 4인 팀 프로젝트
          - SNS 서비스 : 개인 프로젝트

      - title: 인터넷비즈니스 프로그래밍
        caption: 2002.12 - 2003.05
        sub_title: 경원 직업훈련 학교 (정부지원 직업훈련 과정)
        quote: >
          Windows 2000 Server, ASP, MS-SQL 교육 및 교육과정을 활용한 프로젝트 진행
        description: | # this will include new lines to allow paragraphs
          교육 과정 중 습득한 스킬
          - ASP.net, MS-SQL, HTML, CSS
          - Photoshop, Illustrator 활용
          교육 과정 중 진행한 프로젝트
          - 온라인 Book 쇼핑몰 사이트 : 개인 프로젝트

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
